name: Push-To-Main
on: push

jobs:
  push-to-main:
    name: pycode
    runs-on: ubuntu-latest
    steps:
      -name: checkout code
       uses: actions/checkout@v2

       env:
         DEFAULT_BRANCH:main
         GIHUB_TOKEN:${{secrets.GITHUB_TOKEN}}
         
