name: Push-To-Main
on: push

jobs:
  push-to-main:
    name: pycode
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up environment variables
        run: |
          echo "DEFAULT_BRANCH=main" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}" >> $GITHUB_ENV
